version: "3.7"

volumes:
  db-data:
  pgadmin:

services:
  pindrop-backend:
    image: node:12-alpine
    working_dir: /home/node/app
    command: "npm run start:dev"
    volumes:
      - .:/home/node/app
    ports:
      - 3000:3000

  db:
    image: postgres:11
    restart: always
    environment:
      POSTGRES_DB: pindrop
      POSTGRES_PASSWORD: pindropdev
      POSTGRES_USER: pindrop
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - 5432:5432

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
    logging:
      driver: none 
    volumes:
       - pgadmin:/root/.pgadmin
    ports:
      - "${PGADMIN_PORT:-5050}:80"
    restart: unless-stopped